# Generated by Django 5.1.4 on 2025-01-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendasprodutos',
            name='produtoFK',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='usuarioFK',
        ),
        migrations.RemoveField(
            model_name='vendasprodutos',
            name='vendaFK',
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
        migrations.DeleteModel(
            name='VendasProdutos',
        ),
    ]
