# Generated by Django 5.1.4 on 2025-01-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_vendasprodutos_produtofk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
